"""
Revision ID: 8a456eb97f5d
Revises: 
Create Date: 2025-11-18 14:32:33.198771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a456eb97f5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agents',
    sa.Column('agent_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('agent_uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_agents_policy_id'), 'agents', ['policy_id'], unique=False)
    op.create_table('control_rules',
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('control_id', 'rule_id')
    )
    op.create_index(op.f('ix_control_rules_control_id'), 'control_rules', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_rules_rule_id'), 'control_rules', ['rule_id'], unique=False)
    op.create_table('policy_controls',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('policy_id', 'control_id')
    )
    op.create_index(op.f('ix_policy_controls_control_id'), 'policy_controls', ['control_id'], unique=False)
    op.create_index(op.f('ix_policy_controls_policy_id'), 'policy_controls', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_controls_policy_id'), table_name='policy_controls')
    op.drop_index(op.f('ix_policy_controls_control_id'), table_name='policy_controls')
    op.drop_table('policy_controls')
    op.drop_index(op.f('ix_control_rules_rule_id'), table_name='control_rules')
    op.drop_index(op.f('ix_control_rules_control_id'), table_name='control_rules')
    op.drop_table('control_rules')
    op.drop_index(op.f('ix_agents_policy_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('rules')
    op.drop_table('policies')
    op.drop_table('controls')
    # ### end Alembic commands ###
